### ISSUE TITLE
文字位置

### ISSUE THREAD

**Issue by vsxen** [Artwalk/GO-ZhihuDaily#6]
文字放到图片上，经常看不清楚，能改进一下吗？

**Comment by Artwalk** [comment]
你说的这个开始比较奇怪，因为 Mac 无论是 Safari 还是 Chrome *经常看不清*都有点太夸张了，然后去 Win下看了下，发现 IE 11 显示的不正常
所以能提供下 系统 版本 浏览器 吗？

**Comment by vnexus** [comment]
不好意思，现在才来补充
机器人那个，明显看不清楚标题，
![QQ20150827-1@2x.png](https://ooo.0o0.ooo/2015/08/27/55df180dd2e45.png "QQ20150827-1@2x.png")
![QQ20150827-2@2x.png](https://ooo.0o0.ooo/2015/08/27/55df180dda04e.png "QQ20150827-2@2x.png")
不如采用这样，文字放在图片下方？
![QQ20150827-3@2x.png](https://ooo.0o0.ooo/2015/08/27/55df180dbf618.png "QQ20150827-3@2x.png")

**Comment by vnexus** [comment]
我一般只用chrome

**Comment by TheWaWaR** [comment]
这也叫看不清么。。。

**Comment by vnexus** [comment]
https://github.com/nonoroazoro/Zhihu-Daily-Reader
另一个日报
