### ISSUE TITLE
我想问下你是怎么获取知乎日报的图片的

### ISSUE THREAD

**Issue by humucai** [Artwalk/GO-ZhihuDaily#8]
直接引用就是403forbid

**Comment by Artwalk** [comment]
应该是做了防盗，可以通过代码抓到自己服务器上


Original Message
Sender:pinkyellonotifications@github.com
Recipient:Artwalk/GO-ZhihuDailyGO-ZhihuDaily@noreply.github.com
Date:Saturday, Jan 2, 2016 01:22
Subject:[GO-ZhihuDaily] 我想问下你是怎么获取知乎日报的图片的 (#8)


直接引用就是403forbid
